### ISSUE TITLE
KeyError: 'PATH_TO_MATLAB' when install a package

### ISSUE THREAD

**Issue by ghost** [vadimkantorov/wigwam#3]
I run  `wigwam install vlfeat` and get error informations as follows：

Unhandled exception occured!

Please consider filing a bug report at http://github.com/vadimkantorov/wigwam/issues
Please paste the stack trace below into the issue.

==STACK_TRACE_BEGIN==

Traceback (most recent call last):
  File "/dev/fd/63", line 1090, in <module>
  File "/dev/fd/63", line 646, in install
  File "/dev/fd/63", line 676, in build
  File "/dev/fd/63", line 614, in lint
  File "/dev/fd/63", line 496, in **init**
  File "<string>", line 9, in setup
  File "/dev/fd/63", line 338, in cfg
KeyError: 'PATH_TO_MATLAB'

===STACK_TRACE_END===

**Comment by vadimkantorov** [comment]
As the error obscurely suggesting, you need to run instead: `wigwam install vlfeat -DPATH_TO_MATLAB=/path/to/your/bin/matlab`

But I haven't worked with vlfeat for a long time, so its installation may be broken. Feel free to leave a comment in this thread if it doesn't work.

**Comment by vadimkantorov** [comment]
Closing the issue.
